### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by MJP1973** [Gamechecker6745/SnakeReloaded#2]
Hi Gamechecker, 

It would be really good to have an update of this amazing game. I want to play it with my friends over the internet. 

Is this possible?

Thank you

**Comment by Gamechecker6745** [comment]
Hi MJP973,
Multiplayer is a worked upon idea however there are various limitations.  In order for multiplayer to work, the players need to communicate with a global server and this may create lag and security risks.  I am sorry but the idea of multiplayer from different computers may not be possible at this point in time. Gamechecker6745

**Comment by MJP1973** [comment]
Thats OK gamechecker. thanks for getting back to me
